//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWA_Aplikacija.AdventureWorksOBP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdventureWorksOBPEntities : DbContext
    {
        public AdventureWorksOBPEntities()
            : base("name=AdventureWorksOBPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Drzava> Drzave { get; set; }
        public virtual DbSet<Grad> Gradovi { get; set; }
        public virtual DbSet<Kategorija> Kategorije { get; set; }
        public virtual DbSet<Komercijalist> Komercijalisti { get; set; }
        public virtual DbSet<KreditnaKartica> KreditnaKartice { get; set; }
        public virtual DbSet<Kupac> Kupci { get; set; }
        public virtual DbSet<Potkategorija> Potkategorije { get; set; }
        public virtual DbSet<prodavac> prodavacs { get; set; }
        public virtual DbSet<Proizvod> Proizvodi { get; set; }
        public virtual DbSet<Racun> Racuni { get; set; }
        public virtual DbSet<Stavka> Stavke { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<VozniRed> VozniReds { get; set; }
    }
}
