//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWA_Aplikacija.AdventureWorksOBP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Proizvod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvod()
        {
            this.Stavkas = new HashSet<Stavka>();
        }
    
        public int IDProizvod { get; set; }
        [Required(ErrorMessage = "Naziv je obavezan")]
        public string Naziv { get; set; }
        [Required(ErrorMessage = "BrojProizvoda je obavezan")]
        public string BrojProizvoda { get; set; }
        [Required(ErrorMessage = "Boja je obavezan")]
        public string Boja { get; set; }
        [Required(ErrorMessage = "MinimalnaKolicinaNaSkladistu je obavezan")]
        //[Range(typeof(int), "0", "2147483647")]
        public short MinimalnaKolicinaNaSkladistu { get; set; }
        [Required(ErrorMessage = "CijenaBezPDV je obavezan")]
        //[Range(typeof(int), "0", "2147483647")]
        public decimal CijenaBezPDV { get; set; }
        [Required(ErrorMessage = "Potkategorija je obavezna")]
        [Display(Name = "Potkategorija")]
        public Nullable<int> PotkategorijaID { get; set; }
    
        public virtual Potkategorija Potkategorija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stavka> Stavkas { get; set; }
    }
}
