//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWA_Aplikacija.AdventureWorksOBP
{
    using System;
    using System.Collections.Generic;
    
    public partial class VozniRed
    {
        public int IDVozniRed { get; set; }
        public string Stanica { get; set; }
        public Nullable<System.TimeSpan> Polazak { get; set; }
    }
}
